main: add ability to skip photos and/or videos
Skip videos by default. There are videos in the photos list and they
cause the following error.

Error: Failed to parse blah.mp4 first two bytes is not a SOI marker